# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu-sync" do
  name "emu-sync"
  desc "Sync ROMs and BIOS files from an S3-compatible bucket"
  homepage "https://github.com/jacobfgrant/emu-sync"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu-sync"

  on_macos do
    on_intel do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_darwin_amd64.tar.gz"
      sha256 "d7dd7290d9f5263a65fb5d6c8fb7ef3c8f7a80875279412623ed16c3aa23f074"
    end
    on_arm do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_darwin_arm64.tar.gz"
      sha256 "f07313ac360a0aa0365f04376e02c25ad361dbca6a60e62e047fdfe6a99fd2c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_linux_amd64.tar.gz"
      sha256 "7e64a2dff2690a456c2bf6ddfe738da2902460f92ae2933c9f3778d4d2ae8eae"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emu-sync"]
  end

  # No zap stanza required
end
