# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu-sync" do
  name "emu-sync"
  desc "Sync ROMs and BIOS files from an S3-compatible bucket"
  homepage "https://github.com/jacobfgrant/emu-sync"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu-sync"

  on_macos do
    on_intel do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_darwin_amd64.tar.gz"
      sha256 "61ed14c228e7ef933b0498096d90cd24a1d166fb08c4114ea5137fcada4fc0fc"
    end
    on_arm do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_darwin_arm64.tar.gz"
      sha256 "f3d846bd847d7b6b4c86ee17f64cee3efe1bd97eb41017e42b5a35e0afd373fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_linux_amd64.tar.gz"
      sha256 "d0009d29226ec02ebcca0fb23153d3c9cf130f21079171a06cf7c1e5a75c8e63"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emu-sync"]
  end

  # No zap stanza required
end
