# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu-sync" do
  name "emu-sync"
  desc "Sync ROMs and BIOS files from an S3-compatible bucket"
  homepage "https://github.com/jacobfgrant/emu-sync"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu-sync"

  on_macos do
    on_intel do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_darwin_amd64.tar.gz"
      sha256 "ab09ba201eacb268ba5b79e32dcbea843b386bed586d25cce18f95de48bbaa54"
    end
    on_arm do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_darwin_arm64.tar.gz"
      sha256 "92e2b19d81c8f7debb9f0f526565adad0082277c3be09b3a2b6f7b0ce33ed6d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jacobfgrant/emu-sync/releases/download/v#{version}/emu-sync_linux_amd64.tar.gz"
      sha256 "ad9b5243bc0d8f6194971e59ba527c888eeeb9d7c84b09badddb2f74315bf00e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emu-sync"]
  end

  # No zap stanza required
end
